// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BulkActionBar: typeof import('./src/components/BulkActionBar.vue')['default']
    MailTable: typeof import('./src/components/MailTable.vue')['default']
    MailView: typeof import('./src/components/MailView.vue')['default']
    ModalView: typeof import('./src/components/ModalView.vue')['default']
  }
}

export { }
